### ISSUE TITLE
Remove default values

### ISSUE THREAD

**Issue by smith6jt-cop** [faryabiLab/AnnoSpat#4]
Default value for suffix is still "_IMC_T1D_AnnoSpat"

**Comment by aanchalMongia** [comment]
Thanks for your suggestion, since the dataset could be of any type, we have now updated the code and readme to reflect the updated suffix (set to "_Data_AnnoSpat").

**Comment by smith6jt-cop** [comment]
Also, if the number of expected cell types is greater than the number you have in adaptive_th_vec_str it will force:

`Traceback (most recent call last):
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/bin/AnnoSpat", line 8, in <module>
    sys.exit(main())
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/AnnoSpat/run.py", line 98, in main
    app()
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/AnnoSpat/run.py", line 78, in anno
    classify_IMCcells.anno(data_path, signature_path, op_dir, p1, p2, toDrop, roi_name_col,disease_status_col,classifier,th,adaptive_th_vec,   sampling_ratio,suffix,fileseparator)
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/AnnoSpat/classify_IMCcells.py", line 108, in anno
    (assigned_centroids,centroids,good_cells_ind_allcts_list) = initial_labelling(assigned_centroids, centroids, imc_forSSC, signatures, dec_abudance_ind, th,adaptive_th_vec)
  File "/home/smith6jt/anaconda3/envs/AnnoSpat2/lib/python3.6/site-packages/AnnoSpat/dependencies/helper_functions.py", line 114, in initial_labelling
    adaptive_th=adaptive_th_vec[i]
IndexError: list index out of range`

Increasing the number of values in the list to correspond to the number of expected cell types solves the problem.

**Comment by aanchalMongia** [comment]
Hi @smith6jt-cop , the number of values in  "adaptive_th_vec_str" is assumed to be the same as no of cell types as each value by definition correspond to the threshold to be taken for each cell type.
We have now explicitly mentioned this in Readme too to avoid confusion.
Thanks for the suggestion.
